# -*- coding: utf-8 -*-
"""myInfo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mV6qSbqjw4J1VUd5LqJAupxtd8vmwqKn
"""

# CS175-50
# Bilquis Haq

print("I'm in the class")
print(8+6)
print("My major is Computer Science")